<?php
/**
 * Acceptance verification (spec §63) — simulates a real MCP client
 * session end-to-end through the JSON-RPC layer, exactly like
 * ChatGPT/Claude/Cursor would.
 *
 * Run: php tests/acceptance.php
 *
 * @package AIOS\Tests
 */

declare( strict_types=1 );

require_once __DIR__ . '/bootstrap.php';
require_once __DIR__ . '/TestCase.php';

$pass = function ( string $label ): void {
	printf( "  [PASS] %s\n", $label );
};
$fail = function ( string $label, string $detail = '' ): void {
	printf( "  [FAIL] %s%s\n", $label, '' !== $detail ? " — {$detail}" : '' );
	exit( 1 );
};

// Reset to a clean state.
__reset_shim();
$GLOBALS['__wp_shim']['options']['ai_os_settings'] = array();

$property = new ReflectionProperty( AIOS\Core\Plugin::class, 'instance' );
$property->setAccessible( true );
$property->setValue( null, null );
global $ai_wp_os;
$ai_wp_os = new AIOS\Core\Plugin();
$ai_wp_os->boot();
__run_hook( 'plugins_loaded' );

$container = AIOS\Core\Plugin::instance()->container();
$server    = $container->get( AIOS\Mcp\Server::class );
$user      = new WP_User( 1 );

echo "AI WordPress OS — acceptance run (spec §63)\n";
echo str_repeat( '-', 60 ) . "\n";

// ---- 1. initialize handshake (like a fresh client connection).
$request  = AIOS\Mcp\Protocol\JsonRpcRequest::fromDecoded( array(
	'jsonrpc' => '2.0',
	'id'      => 1,
	'method'  => 'initialize',
	'params'  => array( 'protocolVersion' => '2025-06-18' ),
) );
$response = $server->dispatch( $request, $user, 'acceptance' );
$body     = $response->toArray();
( 'ai-wordpress-os' === ( $body['result']['serverInfo']['name'] ?? '' ) )
	? $pass( 'MCP initialize handshake' )
	: $fail( 'MCP initialize handshake', wp_json_encode( $body ) );

// ---- 2. tools/list discovery.
$request  = AIOS\Mcp\Protocol\JsonRpcRequest::fromDecoded( array(
	'jsonrpc' => '2.0', 'id' => 2, 'method' => 'tools/list',
) );
$response = $server->dispatch( $request, $user, 'acceptance' );
$tools    = $response->toArray()['result']['tools'] ?? array();
count( $tools ) > 20
	? $pass( 'tool discovery (' . count( $tools ) . ' tools exposed)' )
	: $fail( 'tool discovery', 'too few tools' );

// ---- 3. AI inspects the site.
$call = function ( array $params ) use ( $server, $user ): array {
	$request  = AIOS\Mcp\Protocol\JsonRpcRequest::fromDecoded( array(
		'jsonrpc' => '2.0', 'id' => 99, 'method' => 'tools/call', 'params' => $params,
	) );
	$response = $server->dispatch( $request, $user, 'acceptance' );
	return $response->toArray()['result'] ?? array();
};

$site = $call( array( 'name' => 'site.get_info', 'arguments' => array() ) );
( isset( $site['structuredContent']['site'] ) )
	? $pass( 'AI inspects site info' )
	: $fail( 'AI inspects site info', wp_json_encode( $site ) );

$map = $call( array( 'name' => 'context.get_site_map', 'arguments' => array() ) );
( isset( $map['structuredContent']['theme'] ) )
	? $pass( 'AI reads structured site map' )
	: $fail( 'AI reads structured site map' );

// ---- 4. AI safely creates content.
$created = $call( array(
	'name'      => 'content.create_post',
	'arguments' => array( 'title' => 'Acceptance Post', 'content' => '<p>Generated by AI OS</p>', 'status' => 'draft' ),
) );
$post_id = $created['structuredContent']['id'] ?? 0;
$post_id > 0
	? $pass( "AI creates content (post #{$post_id})" )
	: $fail( 'AI creates content', wp_json_encode( $created ) );

// ---- 5. AI attempts a destructive action → approval, not execution.
$delete = $call( array( 'name' => 'content.delete_post', 'arguments' => array( 'id' => $post_id ) ) );
( 'approval_required' === ( $delete['structuredContent']['status'] ?? '' ) )
	? $pass( 'destructive action queued for approval, NOT executed' )
	: $fail( 'approval gating', wp_json_encode( $delete ) );
( 'trash' === ( $GLOBALS['__wp_shim']['posts'][ $post_id ]['post_status'] ?? '' ) )
	? $fail( 'post must not be trashed before approval' )
	: $pass( 'post untouched before approval' );

// ---- 6. Human approves via the approval queue.
$approval_id = $delete['structuredContent']['approval_id'];
$approvals   = $container->get( AIOS\Database\Repositories\ApprovalRepository::class );
$approval    = $approvals->claimPending( $approval_id, 'approved', 1 );
null !== $approval
	? $pass( 'human claims and approves the request' )
	: $fail( 'approval claim' );

$tools     = $container->get( AIOS\Tools\ToolRegistry::class );
$executor  = $container->get( AIOS\Tools\ToolExecutor::class );
$executed  = $executor->executeApproved( $tools->get( 'content.delete_post' ), array( 'id' => $post_id ), $user, $approval_id );
( $executed->ok() && 'trash' === ( $GLOBALS['__wp_shim']['posts'][ $post_id ]['post_status'] ?? '' ) )
	? $pass( 'approved action executes (post → trash, restorable)' )
	: $fail( 'approved execution', wp_json_encode( $executed->toArray() ) );

// ---- 7. Audit trail shows the full story.
$logs = $container->get( AIOS\Audit\AuditLogger::class );
$rows = $logs->repository()->query( array( 'tool' => 'content.delete_post' ) );
$story = array_column( $rows, 'status' );
( in_array( 'approval_required', $story, true ) && in_array( 'ok', $story, true ) )
	? $pass( 'audit log records the full approval → execution story' )
	: $fail( 'audit story', wp_json_encode( $story ) );

// ---- 8. Path traversal blocked at MCP layer.
$traversal = $call( array( 'name' => 'theme.read_file', 'arguments' => array( 'file' => '../../../../../wp-config.php' ) ) );
( ( $traversal['isError'] ?? true ) === true )
	? $pass( 'path traversal blocked through the MCP surface' )
	: $fail( 'path traversal defense' );

// ---- 9. Secrets never appear in tool output.
$env = wp_json_encode( $call( array( 'name' => 'site.get_environment', 'arguments' => array() ) ) );
( ! str_contains( (string) $env, 'DB_PASSWORD' ) )
	? $pass( 'secrets never exposed to the AI client' )
	: $fail( 'secret exposure' );

// ---- 10. Unauthenticated principals get nothing.
$anon_request  = AIOS\Mcp\Protocol\JsonRpcRequest::fromDecoded( array(
	'jsonrpc' => '2.0', 'id' => 3, 'method' => 'tools/call',
	'params'  => array( 'name' => 'site.get_info' ),
) );
$anon_response = $server->dispatch( $anon_request, new WP_User( 0 ), 'acceptance' );
$anon_body     = $anon_response->toArray();
( ( $anon_body['result']['isError'] ?? true ) === true )
	? $pass( 'unauthenticated principals are denied' )
	: $fail( 'anonymous access must be denied' );

echo str_repeat( '-', 60 ) . "\n";
echo "ACCEPTANCE: all checks passed.\n";
